server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: adminadmin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://oymbsfyp:nhqSQsWPX1Oz0KExrmN7AjKhNI4iO7-k@gull.rmq.cloudamqp.com/oymbsfyp

logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: debug
    org.hibernate: info

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course



management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
